import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import"./style.css";
const APPS=[{id:"files",name:"Files",icon:"📁",title:"파일 관리자"},{id:"notes",name:"Notes",icon:"📝",title:"메모"},{id:"terminal",name:"Terminal",icon:"⌨️",title:"터미널"},{id:"settings",name:"Settings",icon:"⚙️",title:"설정"},{id:"about",name:"NeoOS",icon:"◈",title:"NeoOS 정보"}];
function App(){
const[windows,setWindows]=useState([]),[active,setActive]=useState(null),[boot,setBoot]=useState(true),[dark,setDark]=useState(()=>localStorage.getItem("neoos-dark")!=="false"),[wall,setWall]=useState(()=>localStorage.getItem("neoos-wall")||"aurora"),[files,setFiles]=useState(()=>JSON.parse(localStorage.getItem("neoos-files")||'{"README.txt":"Welcome to NeoOS v2.0"}')),[note,setNote]=useState(()=>localStorage.getItem("neoos-note")||"NeoOS에 오신 것을 환영합니다."),[query,setQuery]=useState("");
useEffect(()=>{const t=setTimeout(()=>setBoot(false),900);return()=>clearTimeout(t)},[]);
useEffect(()=>localStorage.setItem("neoos-files",JSON.stringify(files)),[files]);useEffect(()=>localStorage.setItem("neoos-note",note),[note]);useEffect(()=>localStorage.setItem("neoos-dark",String(dark)),[dark]);useEffect(()=>localStorage.setItem("neoos-wall",wall),[wall]);
const open=id=>{if(!windows.includes(id))setWindows(w=>[...w,id]);setActive(id)},close=id=>{setWindows(w=>w.filter(x=>x!==id));setActive(a=>a===id?null:a)},toggle=id=>windows.includes(id)?setActive(a=>a===id?null:id):open(id);
const names=useMemo(()=>Object.keys(files).sort(),[files]),filtered=APPS.filter(a=>a.name.toLowerCase().includes(query.toLowerCase()));
if(boot)return <div className="boot"><div className="boot-logo">◈</div><h1>NEO<span>OS</span></h1><p>Starting Web System...</p><div className="loader"/></div>;
return <main className={"os "+(dark?"dark":"light")+" wall-"+wall}>
<div className="topbar"><div className="top-brand">◈ <b>NeoOS</b></div><div className="top-center">{new Date().toLocaleDateString("ko-KR",{weekday:"short",month:"long",day:"numeric"})}</div><div className="top-right"><span>● ONLINE</span><span>{new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"})}</span></div></div>
<section className="desktop"><div className="welcome"><div><p className="eyebrow">NEOOS WEB SYSTEM</p><h1>Welcome back.</h1><p>오늘도 NeoOS를 개발해보자 🚀</p></div><button onClick={()=>open("about")}>시스템 정보 →</button></div>
<div className="icons">{filtered.map(a=><button className="app-icon" key={a.id} onDoubleClick={()=>open(a.id)} onClick={()=>toggle(a.id)}><span>{a.icon}</span><small>{a.name}</small></button>)}</div>
{windows.map((id,i)=><Window key={id} app={APPS.find(a=>a.id===id)} index={i} active={active===id} onFocus={()=>setActive(id)} onClose={()=>close(id)}><AppContent id={id} files={files} setFiles={setFiles} note={note} setNote={setNote} dark={dark} setDark={setDark} wall={wall} setWall={setWall} names={names}/></Window>)}</section>
<div className="dock">{APPS.map(a=><button key={a.id} className={active===a.id?"selected":""} onClick={()=>toggle(a.id)} title={a.title}>{a.icon}</button>)}<i/><button onClick={()=>setQuery(query?"":" ")}>🔎</button></div>
{query!==""&&<div className="search"><input autoFocus placeholder="NeoOS에서 검색..." value={query.trim()===""?"":query} onChange={e=>setQuery(e.target.value)}/><div>{filtered.map(a=><button key={a.id} onClick={()=>{open(a.id);setQuery("")}}>{a.icon} {a.name}</button>)}</div></div>}</main>}
function Window({app,index,active,onFocus,onClose,children}){return <div className={"window "+(active?"active":"")} style={{zIndex:active?100:10+index}} onMouseDown={onFocus}><div className="titlebar"><div><span>{app.icon}</span><b>{app.title}</b></div><button onClick={onClose}>×</button></div><div className="window-body">{children}</div></div>}
function AppContent({id,files,setFiles,note,setNote,dark,setDark,wall,setWall,names}){
if(id==="files")return <div className="files"><div className="file-head"><b>내 파일</b><button onClick={()=>setFiles(f=>({...f,["새파일-"+Date.now()+".txt"]:""}))}>＋ 새 파일</button></div>{names.map(n=><div className="file-row" key={n}><span>📄</span><b>{n}</b><small>{files[n]?.length||0} bytes</small></div>)}</div>;
if(id==="notes")return <div className="notes"><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="메모를 입력하세요..."/><small>자동 저장됨 · localStorage</small></div>;
if(id==="settings")return <div className="settings"><h2>Settings</h2><label>테마 <button onClick={()=>setDark(!dark)}>{dark?"🌙 Dark":"☀️ Light"}</button></label><label>배경 <select value={wall} onChange={e=>setWall(e.target.value)}><option value="aurora">Aurora</option><option value="midnight">Midnight</option><option value="sky">Sky</option></select></label><div className="setting-card"><b>NeoOS v2.0</b><span>브라우저 저장소 기반 개인 웹 OS</span></div></div>;
if(id==="terminal")return <Terminal files={files} setFiles={setFiles}/>;
return <div className="about"><div className="neo-mark">◈</div><h2>NeoOS Web</h2><p>Version 2.0</p><p className="muted">A lightweight web operating system built with React + Vite.</p><div className="chips"><span>Vercel</span><span>React</span><span>Mobile Ready</span><span>Local Storage</span></div></div>}
function Terminal({files,setFiles}){const[out,setOut]=useState(["NeoOS Shell v2.0","Type help to begin."]),[input,setInput]=useState("");
const run=cmd=>{const[p,...a]=cmd.trim().split(/\s+/);if(!p)return;let o="";switch(p){case"help":o="help  ls  cat  touch  rm  clear  neofetch  status  date";break;case"ls":o=Object.keys(files).join("  ");break;case"cat":o=files[a[0]]??"파일 없음";break;case"touch":if(a[0]){setFiles(f=>({...f,[a[0]]:""}));o=a[0]+" created"}else o="usage: touch FILE";break;case"rm":if(a[0]){setFiles(f=>{const n={...f};delete n[a[0]];return n});o=a[0]+" removed"}break;case"neofetch":o="NeoOS Web 2.0\nShell: neo-shell\nRuntime: Browser\nStorage: localStorage";break;case"status":o="SYSTEM ONLINE\nAPPS READY\nSTORAGE READY";break;case"date":o=new Date().toLocaleString("ko-KR");break;case"clear":setOut([]);return;default:o="neo-shell: command not found: "+p}setOut(x=>[...x,"neo@neoos:~$ "+cmd,o])};
return <div className="terminal"><div className="term-out">{out.map((x,i)=><div key={i}>{x}</div>)}</div><div className="term-input"><span>neo@neoos:~$</span><input autoFocus value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){run(input);setInput("")}}}/></div></div>}
createRoot(document.getElementById("root")).render(<App/>);