name: Windows Cloud PC - AnyDesk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download & Install AnyDesk
      run: |
        Invoke-WebRequest -Uri "https://download.anydesk.com/AnyDesk.exe" -OutFile "AnyDesk.exe"
        Start-Process -FilePath ".\AnyDesk.exe" -ArgumentList "--install `"$env:ProgramFiles (x86)\AnyDesk`" --start-with-win --silent" -Wait

    - name: Setup AnyDesk Password
      run: |
        $anydesk = "$env:ProgramFiles (x86)\AnyDesk\AnyDesk.exe"
        cmd /c "echo joyzonetech | `"$anydesk`" --set-password"

    - name: Log To AnyDesk
      run: |
        $anydesk = "$env:ProgramFiles (x86)\AnyDesk\AnyDesk.exe"
        Start-Sleep -Seconds 5
        $ID = & $anydesk --get-id
        Write-Host "===================================="
        Write-Host "AnyDesk ID: $ID"
        Write-Host "AnyDesk Password: joyzonetech"
        Write-Host "===================================="

    - name: Keep Alive
      run: |
        $timeout = 21600
        Start-Sleep -Seconds $timeout
