name: Windows Cloud PC - AnyDesk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download & Install AnyDesk
      run: |
        Invoke-WebRequest -Uri "https://download.anydesk.com/AnyDesk.exe" -OutFile "AnyDesk.exe"
        .\AnyDesk.exe --install "C:\Program Files (x86)\AnyDesk" --start-with-win --silent
        
    - name: Setup AnyDesk Password
      run: |
        cmd /c "echo joyzonetech| ''C:\Program Files (x86)\AnyDesk\AnyDesk.exe'' --set-password"
        
    - name: Log To AnyDesk
      run: |
        $ID = cmd /c "''C:\Program Files (x86)\AnyDesk\AnyDesk.exe'' --get-id"
        Write-Host "===================================="
        Write-Host "AnyDesk ID: $ID"
        Write-Host "AnyDesk Password: joyzonetech"
        Write-Host "===================================="

    - name: Keep Alive
      run: |
        $timeout = 21600
        Start-Sleep -Seconds $timeout
