name: Linux Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Linux
        run: |
          echo "=== Linux Runner ==="
          uname -a
          cat /etc/os-release
          echo
          echo "=== Files ==="
          ls -la

      - name: Start SSH terminal
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
          timeout-minutes: 30
